const user = {
  USER_STORE: 'USER_STORE',
  USER_UPDATE: 'USER_UPDATE',
  USER_REMOVE: 'USER_REMOVE',
};

const users = {
  USERS_FETCH: 'USERS_FETCH',
  USERS_STORE: 'USERS_STORE',
};

const roles = {
  ROLES_FETCH: 'ROLES_FETCH',
  ROLES_STORE: 'ROLES_STORE',
};

const account = {
  ACCOUNT_FETCH: 'ACCOUNT_FETCH',
  ACCOUNT_FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
  ACCOUNT_SAVE: 'ACCOUNT_SAVE',
};

const app = {
  APP_SET_AUTHENTICATED_STATE: 'APP_SET_AUTHENTICATED_STATE',
  APP_AUTHENTICATION_ERROR: 'APP_AUTHENTICATION_ERROR',
};

export default {
  user,
  users,
  roles,
  account,
  app,
};
