const user = {
  USER_REQUEST: 'USER_REQUEST',
  USER_REQUEST_ERROR: 'USER_REQUEST_ERROR',
  USER_STORE: 'USER_STORE',
  USER_UPDATE: 'USER_UPDATE',
  USER_REMOVE: 'USER_REMOVE',
  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',
  USER_RESET_PASSWORD_ERROR: 'USER_RESET_PASSWORD_ERROR',
};

const users = {
  USERS_FETCH: 'USERS_FETCH',
  USERS_STORE: 'USERS_STORE',
  USERS_COUNT_FETCH: 'USERS_COUNT_FETCH',
  USERS_COUNT_STORE: 'USERS_COUNT_STORE',
};

const roles = {
  ROLES_FETCH: 'ROLES_FETCH',
  ROLES_STORE: 'ROLES_STORE',
};

const account = {
  ACCOUNT_FETCH: 'ACCOUNT_FETCH',
  ACCOUNT_FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
  ACCOUNT_SAVE: 'ACCOUNT_SAVE',
};

const app = {
  APP_SET_AUTHENTICATED_STATE: 'APP_SET_AUTHENTICATED_STATE',
  APP_AUTHENTICATION_ERROR: 'APP_AUTHENTICATION_ERROR',
  APP_REQUEST: 'APP_REQUEST',
  APP_REQUEST_COMPLETED: 'APP_REQUEST_COMPLETED',
};

const product = {
  PRODUCT_REQUEST: 'PRODUCT_REQUEST',
  PRODUCT_REQUEST_ERROR: 'PRODUCT_REQUEST_ERROR',
  PRODUCT_STORE: 'PRODUCT_STORE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_REMOVE: 'PRODUCT_REMOVE',
};

const products = {
  PRODUCTS_FETCH: 'PRODUCTS_FETCH',
  PRODUCTS_STORE: 'PRODUCTS_STORE',
  PRODUCTS_COUNT_FETCH: 'PRODUCTS_COUNT_FETCH',
  PRODUCTS_COUNT_STORE: 'PRODUCTS_COUNT_STORE',
};

const story = {
  STORY_REQUEST: 'STORY_REQUEST',
  STORY_REQUEST_ERROR: 'STORY_REQUEST_ERROR',
  STORY_STORE: 'STORY_STORE',
  STORY_UPDATE: 'STORY_UPDATE',
  STORY_REMOVE: 'STORY_REMOVE',
};

const stories = {
  STORIES_FETCH: 'STORIES_FETCH',
  STORIES_STORE: 'STORIES_STORE',
  STORIES_COUNT_FETCH: 'STORIES_COUNT_FETCH',
  STORIES_COUNT_STORE: 'STORIES_COUNT_STORE',
};

const issue = {
  ISSUE_REQUEST: 'ISSUE_REQUEST',
  ISSUE_REQUEST_ERROR: 'ISSUE_REQUEST_ERROR',
  ISSUE_STORE: 'ISSUE_STORE',
  ISSUE_UPDATE: 'ISSUE_UPDATE',
  ISSUE_REMOVE: 'ISSUE_REMOVE',
};

const issues = {
  ISSUES_FETCH: 'ISSUES_FETCH',
  ISSUES_STORE: 'ISSUES_STORE',
  ISSUES_COUNT_FETCH: 'ISSUES_COUNT_FETCH',
  ISSUES_COUNT_STORE: 'ISSUES_COUNT_STORE',
};

const solution = {
  SOLUTION_REQUEST: 'SOLUTION_REQUEST',
  SOLUTION_REQUEST_ERROR: 'SOLUTION_REQUEST_ERROR',
  SOLUTION_STORE: 'SOLUTION_STORE',
  SOLUTION_UPDATE: 'SOLUTION_UPDATE',
  SOLUTION_REMOVE: 'SOLUTION_REMOVE',
};

const solutions = {
  SOLUTIONS_FETCH: 'SOLUTIONS_FETCH',
  SOLUTIONS_STORE: 'SOLUTIONS_STORE',
};

const mail = {
  MAIL_REQUEST: 'MAIL_REQUEST',
  MAIL_REQUEST_ERROR: 'MAIL_REQUEST_ERROR',
};

const templates = {
  TEMPLATES_FETCH: 'TEMPLATES_FETCH',
  TEMPLATES_STORE: 'TEMPLATES_STORE',
};

export default {
  user,
  users,
  roles,
  account,
  app,
  product,
  products,
  story,
  stories,
  issue,
  issues,
  solution,
  solutions,
  mail,
  templates,
};
