const user = {
  USER_REQUEST: 'USER_REQUEST',
  USER_REQUEST_ERROR: 'USER_REQUEST_ERROR',
  USER_STORE: 'USER_STORE',
  USER_UPDATE: 'USER_UPDATE',
  USER_REMOVE: 'USER_REMOVE',
};

const users = {
  USERS_FETCH: 'USERS_FETCH',
  USERS_STORE: 'USERS_STORE',
};

const roles = {
  ROLES_FETCH: 'ROLES_FETCH',
  ROLES_STORE: 'ROLES_STORE',
};

const account = {
  ACCOUNT_FETCH: 'ACCOUNT_FETCH',
  ACCOUNT_FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
  ACCOUNT_SAVE: 'ACCOUNT_SAVE',
};

const app = {
  APP_SET_AUTHENTICATED_STATE: 'APP_SET_AUTHENTICATED_STATE',
  APP_AUTHENTICATION_ERROR: 'APP_AUTHENTICATION_ERROR',
  APP_REQUEST: 'APP_REQUEST',
  APP_REQUEST_COMPLETED: 'APP_REQUEST_COMPLETED',
};

const product = {
  PRODUCT_REQUEST: 'PRODUCT_REQUEST',
  PRODUCT_REQUEST_ERROR: 'PRODUCT_REQUEST_ERROR',
  PRODUCT_STORE: 'PRODUCT_STORE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_REMOVE: 'PRODUCT_REMOVE',
};

const products = {
  PRODUCTS_FETCH: 'PRODUCTS_FETCH',
  PRODUCTS_STORE: 'PRODUCTS_STORE',
};

const story = {
  STORY_REQUEST: 'STORY_REQUEST',
  STORY_REQUEST_ERROR: 'STORY_REQUEST_ERROR',
  STORY_STORE: 'STORY_STORE',
  STORY_UPDATE: 'STORY_UPDATE',
  STORY_REMOVE: 'STORY_REMOVE',
};

const stories = {
  STORIES_FETCH: 'STORIES_FETCH',
  STORIES_STORE: 'STORIES_STORE',
};

const issue = {
  ISSUE_REQUEST: 'ISSUE_REQUEST',
  ISSUE_REQUEST_ERROR: 'ISSUE_REQUEST_ERROR',
  ISSUE_STORE: 'ISSUE_STORE',
  ISSUE_UPDATE: 'ISSUE_UPDATE',
  ISSUE_REMOVE: 'ISSUE_REMOVE',
};

const issues = {
  ISSUES_FETCH: 'ISSUES_FETCH',
  ISSUES_STORE: 'ISSUES_STORE',
};

export default {
  user,
  users,
  roles,
  account,
  app,
  product,
  products,
  story,
  stories,
  issue,
  issues,
};
